import { Field, Submit, Empty, PageHeader, ResourceState } from '../../components/ui'
import { useFeature } from '../../hooks/useFeature'
import { money, nextMonth, formData } from '../../lib/format'
import { useWorkspace } from '../../app/useWorkspace'

export default function RecurringPage() {
  const { spaceId } = useWorkspace()
  const spacePath = `/api/v1/espacios/${spaceId}`
  const { resource, membersState, members, session, busy, mutate, confirm } = useFeature(`${spacePath}/favoritos`)
  const templates = resource.data
  const peopleSelect = (name, label, value = session.usuario.id) => <Field label={label}><select name={name} defaultValue={value} required>{members.map(m => <option key={m.usuarioId} value={m.usuarioId}>{m.nombreUsuario}</option>)}</select></Field>
  return <div className="legacy-feature"><PageHeader title="Gastos recurrentes" /><ResourceState resource={resource}><ResourceState resource={membersState}><section className="card"><h2>Gastos recurrentes</h2><details><summary>Crear plantilla</summary><form className="grid-form" onSubmit={event => { event.preventDefault(); const d = formData(event); for (const k of ['pagadorId', 'montoBase', 'montoVariable', 'frecuenciaAjusteMeses']) d[k] = Number(d[k]); mutate(`${spacePath}/favoritos`, 'POST', d, 'Plantilla creada.') }}>
            <Field label="Nombre" name="nombre" required minLength={2} maxLength={100} />{peopleSelect('pagadorId', 'Pagador')}<Field label="Monto base" name="montoBase" type="number" min="0" step="0.01" required /><Field label="Monto variable" name="montoVariable" type="number" min="0" step="0.01" defaultValue="0" required /><Field label="Revisar cada (meses)" name="frecuenciaAjusteMeses" type="number" min="1" defaultValue="1" required /><Field label="Próxima revisión" name="fechaProximaRevision" type="date" defaultValue={nextMonth()} required /><Field label="Reparto"><select name="reglaDivision"><option value="EQUITATIVA">Equitativo</option><option value="PROPORCIONAL_INGRESOS">Proporcional a ingresos</option></select></Field><Submit busy={busy}>Crear plantilla</Submit>
          </form></details>{templates.map(p => <article className="expense" key={p.id}><div className="row"><div><strong>{p.nombre}</strong><small>Revisión: {p.fechaProximaRevision} {p.vencido ? '· VENCIDA' : ''}</small></div><strong>{money(Number(p.montoBase) + Number(p.montoVariable))}</strong><button disabled={busy || p.vencido} onClick={() => mutate(`/api/v1/favoritos/${p.id}/ejecutar`, 'POST', undefined, 'Gasto generado.')}>Generar gasto</button><button disabled={busy} className="danger" onClick={async () => { if (await confirm('¿Eliminar esta plantilla?')) mutate(`/api/v1/favoritos/${p.id}`, 'DELETE', undefined, 'Plantilla eliminada.') }}>Eliminar</button></div><details><summary>Actualizar monto y revisión</summary><form className="grid-form" onSubmit={event => { event.preventDefault(); const d = formData(event); d.nuevoMontoBase = Number(d.nuevoMontoBase); d.nuevoMontoVariable = Number(d.nuevoMontoVariable); mutate(`/api/v1/favoritos/${p.id}/actualizar-monto`, 'PUT', d, 'Plantilla actualizada.') }}><Field label="Monto base" name="nuevoMontoBase" type="number" min="0" step="0.01" defaultValue={p.montoBase} required /><Field label="Variable" name="nuevoMontoVariable" type="number" min="0" step="0.01" defaultValue={p.montoVariable} required /><Field label="Nueva revisión" name="nuevaFechaProximaRevision" type="date" defaultValue={nextMonth()} required /><Submit busy={busy}>Actualizar</Submit></form></details></article>)}{!templates.length && <Empty>No hay plantillas todavía.</Empty>}</section></ResourceState></ResourceState></div>
}
